-- =============================================================================
-- ParkWatch — Database Schema (MySQL 8.0)
-- OCR-Assisted Citizen Parking Violation Reporting System, Malate District
--
-- Column names and types follow the official ERD exactly.
-- Extra columns (fcm_token, barangay_id in VIOLATION_REPORTS, vehicle_type)
-- are marked with -- [ext] and are needed by the application but not shown
-- in the ERD diagram for brevity.
--
-- Run order (FK dependency):
--   BARANGAYS → STREETS → USERS → VEHICLES → PENALTY_TIERS
--   → VIOLATION_REPORTS → PARKING_RULES → NOTIFICATION_LOG
--
-- Executed automatically by the MySQL Docker container on first startup
-- (mounted as /docker-entrypoint-initdb.d/01-schema.sql).
-- =============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ─── 1. BARANGAYS ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS BARANGAYS (
  barangay_id      INT          NOT NULL AUTO_INCREMENT,
  barangay_name    VARCHAR(100) NOT NULL,
  barangay_number  VARCHAR(10),
  is_participating BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (barangay_id),
  UNIQUE KEY uq_barangay_name (barangay_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─── 2. STREETS ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS STREETS (
  street_id   INT          NOT NULL AUTO_INCREMENT,
  barangay_id INT          NOT NULL,
  street_name VARCHAR(100) NOT NULL,
  is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (street_id),
  CONSTRAINT fk_streets_barangay
    FOREIGN KEY (barangay_id) REFERENCES BARANGAYS (barangay_id) ON DELETE CASCADE,
  UNIQUE KEY uq_street_per_barangay (barangay_id, street_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─── 3. USERS ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS USERS (
  user_id         INT         NOT NULL AUTO_INCREMENT,
  first_name      VARCHAR(50) NOT NULL,
  last_name       VARCHAR(50) NOT NULL,
  email           VARCHAR(100) NOT NULL,
  password_hash   CHAR(60)    NOT NULL,                  -- bcrypt always produces 60 chars
  phone_number    VARCHAR(20),
  role            ENUM('citizen','brgy_official','mtpb_officer','mtpb_supervisor','admin')
                    NOT NULL DEFAULT 'citizen',
  anonymous_alias VARCHAR(50),                           -- public handle, generated by app
  barangay_id     INT,                                   -- assigned barangay (officials/officers)
  fcm_token       VARCHAR(255),                          -- [ext] Firebase device token for push notifications
  is_verified     BOOLEAN     NOT NULL DEFAULT FALSE,
  is_active       BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at      DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id),
  CONSTRAINT fk_users_barangay
    FOREIGN KEY (barangay_id) REFERENCES BARANGAYS (barangay_id) ON DELETE SET NULL,
  UNIQUE KEY uq_users_email (email),
  UNIQUE KEY uq_users_alias (anonymous_alias)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─── 4. VEHICLES ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS VEHICLES (
  vehicle_id         INT         NOT NULL AUTO_INCREMENT,
  plate_number       VARCHAR(20) NOT NULL,
  vehicle_type       ENUM('car','motorcycle','truck','van','jeepney','tricycle','other')
                       NOT NULL DEFAULT 'car',           -- [ext] not in ERD; useful for reporting
  color              VARCHAR(30),                        -- [ext] optional visual aid
  total_violations   INT         NOT NULL DEFAULT 0,     -- maintained by app on report resolution
  is_repeat_offender BOOLEAN     NOT NULL DEFAULT FALSE, -- maintained by app (true when total_violations >= 2)
  first_recorded_at  DATETIME,
  created_at         DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (vehicle_id),
  UNIQUE KEY uq_vehicles_plate (plate_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─── 5. PENALTY_TIERS ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS PENALTY_TIERS (
  tier_id           INT           NOT NULL AUTO_INCREMENT,
  tier_name         VARCHAR(50)   NOT NULL,              -- e.g. '1st Offense', '2nd Offense'
  min_violations    INT           NOT NULL,              -- lower bound of violation count for this tier
  max_violations    INT,                                 -- upper bound; NULL = no ceiling
  fine_amount       DECIMAL(10,2) NOT NULL,              -- PHP
  requires_clamping BOOLEAN       NOT NULL DEFAULT FALSE,
  created_at        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (tier_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─── 6. VIOLATION_REPORTS ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS VIOLATION_REPORTS (
  report_id           INT           NOT NULL AUTO_INCREMENT,
  citizen_id          INT,                               -- reporter (NULL = anonymous submission)
  vehicle_id          INT,                               -- resolved after OCR/manual plate match
  street_id           INT,
  barangay_id         INT,                               -- [ext] denormalized from street for faster queries
  violation_type      VARCHAR(100),
  photo_path          VARCHAR(300),                      -- GCS object path, e.g. gs://bucket/reports/uuid.jpg
  ocr_raw_response    TEXT,                              -- full JSON from Google Cloud Vision API
  ocr_extracted_plate VARCHAR(20),                       -- plate text extracted by OCR
  ocr_confidence_score DECIMAL(5,2),                     -- Vision API confidence 0.00–100.00
  manual_plate_input  VARCHAR(20),                       -- citizen-typed plate (fallback / override)
  penalty_tier_id     INT,                               -- assigned after verification
  status              ENUM('pending','verified','acknowledged','dispatched','resolved','rejected')
                        NOT NULL DEFAULT 'pending',
  resolution_outcome  VARCHAR(255),                      -- notes on how it was resolved
  rejection_reason    VARCHAR(255),
  verified_by         INT,                               -- MTPB/brgy user who verified the report
  assigned_officer_id INT,                               -- MTPB officer dispatched to the scene
  is_escalated        BOOLEAN       NOT NULL DEFAULT FALSE,
  ticket_reference    VARCHAR(100),                      -- physical ticket number once issued
  submitted_at        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  verified_at         DATETIME,
  acknowledged_at     DATETIME,
  dispatched_at       DATETIME,
  escalated_at        DATETIME,
  resolved_at         DATETIME,
  created_at          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (report_id),
  CONSTRAINT fk_reports_citizen
    FOREIGN KEY (citizen_id)          REFERENCES USERS (user_id)           ON DELETE SET NULL,
  CONSTRAINT fk_reports_vehicle
    FOREIGN KEY (vehicle_id)          REFERENCES VEHICLES (vehicle_id)     ON DELETE SET NULL,
  CONSTRAINT fk_reports_street
    FOREIGN KEY (street_id)           REFERENCES STREETS (street_id)       ON DELETE SET NULL,
  CONSTRAINT fk_reports_barangay
    FOREIGN KEY (barangay_id)         REFERENCES BARANGAYS (barangay_id)   ON DELETE SET NULL,
  CONSTRAINT fk_reports_penalty_tier
    FOREIGN KEY (penalty_tier_id)     REFERENCES PENALTY_TIERS (tier_id)   ON DELETE SET NULL,
  CONSTRAINT fk_reports_verified_by
    FOREIGN KEY (verified_by)         REFERENCES USERS (user_id)           ON DELETE SET NULL,
  CONSTRAINT fk_reports_officer
    FOREIGN KEY (assigned_officer_id) REFERENCES USERS (user_id)           ON DELETE SET NULL,
  INDEX idx_reports_status          (status),
  INDEX idx_reports_submitted_at    (submitted_at),
  INDEX idx_reports_citizen         (citizen_id),
  INDEX idx_reports_ocr_plate       (ocr_extracted_plate),
  INDEX idx_reports_manual_plate    (manual_plate_input)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─── 7. PARKING_RULES ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS PARKING_RULES (
  rule_id        INT          NOT NULL AUTO_INCREMENT,
  street_id      INT          NOT NULL,
  violation_type VARCHAR(100) NOT NULL,
  is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (rule_id),
  CONSTRAINT fk_rules_street
    FOREIGN KEY (street_id) REFERENCES STREETS (street_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─── 8. NOTIFICATION_LOG ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS NOTIFICATION_LOG (
  notification_id   INT          NOT NULL AUTO_INCREMENT,
  report_id         INT,
  recipient_id      INT,
  message           VARCHAR(500) NOT NULL,
  notification_type ENUM('status_update','escalation','resolution')
                      NOT NULL DEFAULT 'status_update',
  sent_at           DATETIME,
  is_read           BOOLEAN      NOT NULL DEFAULT FALSE,
  read_at           DATETIME,
  created_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (notification_id),
  CONSTRAINT fk_notiflog_report
    FOREIGN KEY (report_id)    REFERENCES VIOLATION_REPORTS (report_id) ON DELETE SET NULL,
  CONSTRAINT fk_notiflog_recipient
    FOREIGN KEY (recipient_id) REFERENCES USERS (user_id)              ON DELETE SET NULL,
  INDEX idx_notiflog_recipient (recipient_id),
  INDEX idx_notiflog_report    (report_id),
  INDEX idx_notiflog_is_read   (is_read)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
